# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - training-attendace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build  
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40679314135645D5845A186E1EED5F5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E1F77BA83324463A12DF68AF6B5F9E5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35A2795F2E1F47D58C3580A0B0689BCC }}

      - name: Zip files preserving symlinks
        run: |
         zip -r deploy.zip .next node_modules package.json public next.config.ts
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'trainings-management'
          slot-name: 'Production'
          package: deploy.zip
